### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by javierelpianista** [Tishacy/SciDownl#14]
When I try to download an article using

    scidownl -D <doi>

I get the following error:

    File "/home/jgarcia/.local/lib/python3.9/site-packages/scidownl/scihub.py", line 112, in find_pdf_in_html
    pdf_url = soup.find('iframe', {'id': 'pdf'}).attrs['src'].split('#')[0]

    AttributeError: 'NoneType' object has no attribute 'attrs'

This didn't happen before. I am using Arch Linux, but also tried in a virtual machine with Linux Mint.
Accessing SciHub manually and downloading the article works.

**Comment by grace-reed** [comment]
Hi Javier,
I am getting a really similar problem because my scidownl does not work either. I am using the same code as you (scidownl -D <doi> . I checked line 112 and see that the AttributeError is caused by beautiful soup and refers to embedding that sci-hub does to papers, placing them in an iframe, then the private function below searches for the embedding and assigns it to the iframe variable. The problem lies in beautiful soup returning NoneType for iframe. It may have renames iframe to something else. My new question lies with the naming through sci hub.

    def _search_direct_url(self, identifier):
        """
        Sci-Hub embeds papers in an iframe. This function finds the actual
        source url which looks something like https://moscow.sci-hub.io/.../....pdf.
        """
        res = self.sess.get(self.base_url + identifier, verify=False)
        s = self._get_soup(res.content)
        iframe = s.find('iframe')
        if iframe:
            return iframe.get('src') if not iframe.get('src').startswith('//') \
                else 'http:' + iframe.get('src')

Grace

**Comment by fridrichmrtn** [comment]
It appears to me, that sci-hub does not use the frames anymore. They utilize divs, see the example below.

`<div id="article">
        <embed type="application/pdf" src="https://twin.sci-hub.se/6279/8a941ec16c0cd4c9ad1bf5ab29139335/ahmed2017.pdf#navpanes=0&amp;view=FitH" id="pdf">
</div>`

**Comment by 15787833237** [comment]
> simply replace `pdf_url = soup.find('iframe', {'id': 'pdf'}).attrs['src'].split('#')[0]` with `pdf_url = soup.find('embed', {'id': 'pdf'}).attrs['src'].split('#')[0]` works for me

Hi，I use python3.9 version , it occurs the same trouble like you mentioned above , and I followed your advise,however, it still didn't work @ddhecnu

**Comment by grace-reed** [comment]
That’s weird there must be some kind of a problem with the eye frame. I’m
not actually sure what the differences between 3.8 and 3.9. I commented and
alternate solution with a different website on the get hub page so thanks
for responding.

**Comment by PhelaPoscam** [comment]
I still get the error in some articles even with iframe to embed change...

> Traceback (most recent call last):
  File "C:\Users\Aleph\PycharmProjects\scihubDown\main.py", line 20, in <module>
    download(DOIs)
  File "C:\Users\Aleph\PycharmProjects\scihubDown\main.py", line 13, in download
    SciHub(doi, out).download(choose_scihub_url_index=1)
  File "C:\Users\Aleph\PycharmProjects\scihubDown\venv\lib\site-packages\scidownl\scihub.py", line 88, in download
    pdf = self.find_pdf_in_html(res.text)
  File "C:\Users\Aleph\PycharmProjects\scihubDown\venv\lib\site-packages\scidownl\scihub.py", line 112, in find_pdf_in_html
    pdf_url = soup.find('embed', {'id': 'pdf'}).attrs['src'].split('#')[0]
AttributeError: 'NoneType' object has no attribute 'attrs'

**Comment by PhelaPoscam** [comment]
I still get the error in some articles even with iframe to embed change

> Traceback (most recent call last):
  File "\main.py", line 20, in <module>
    download(DOIs)
  File "\main.py", line 13, in download
    SciHub(doi, out).download(choose_scihub_url_index=1)
  File "\scihub.py", line 88, in download
    pdf = self.find_pdf_in_html(res.text)
  File "\scihub.py", line 112, in find_pdf_in_html
    pdf_url = soup.find('embed', {'id': 'pdf'}).attrs['src'].split('#')[0]
AttributeError: 'NoneType' object has no attribute 'attrs'

**Comment by fridrichmrtn** [comment]
Great, what about a reproducible example? Just randomly checked the sci-hub, and it seems fine. PDFs flourishing and resting in their embed lane.

**Comment by PhelaPoscam** [comment]
My fault. That the errors were occurring in articles not yet available on scihub. I hadn't realized that was the problem.

**Comment by fridrichmrtn** [comment]
![image](https://user-images.githubusercontent.com/13402178/150332399-a075e01f-ba24-4694-8e79-f3e7d7037f9e.png)
